services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: orders_management_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: orders_management_db
    environment:
      MYSQL_DATABASE: orders_management_mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
